version: "0.2"
ignorePaths: []
dictionaryDefinitions:
  - name: homeassistant
    path: cspell.hass.txt
    addWords: true
dictionaries:
  - python
  - homeassistant
words: []
ignoreWords: []
import: []
enableFiletypes:
  - shellscript
ignoreRegExpList:
  - Email
  - >-
    /ftp:[^\s]*/g
patterns:
  - name: markdown_code_block
    pattern: |
      /
          ^(\s*`{3,}).*     # match the ```
          [\s\S]*?          # the block of code
          ^\1               # end of the block
      /gmx
languageSettings:
  - languageId: markdown
    ignoreRegExpList:
      - markdown_code_block
